<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AdventureTimePatcherCli</AssemblyName>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AdventureTimePatcher.Core\AdventureTimePatcher.Core.csproj" />
  </ItemGroup>
</Project>
